name=cyfney-cpp
version=1.0.5
author=anka
maintainer=anka
sentence=Reusable C++ utilities and base classes.
paragraph=A header-only library providing general-purpose building blocks, common tools, and foundational components for C++ projects.
category=Other
url=https://github.com/cyfney/cyfney-cpp-arduino
architectures=*
includes=cyf.h
depends=
license=MIT